import test from 'node:test';
import assert from 'node:assert/strict';
import {payoffGroups,legPayoff,rate,historyPoints,expectancyMatrix,completedReturn} from '../assets/expected-return.mjs';
import {newStructureLeg} from '../assets/trade-structure.mjs';
import {createCase,savePlan,saveNode,setActivePlan,archiveCase,validateStore,clone} from '../assets/workflow-model.mjs';
const leg=(symbol,type,side,qty,entry,strike='')=>({...newStructureLeg(type,side,qty),underlying:symbol,entry,strike,expiry:type==='stock'?'':'2030-01-01'});
const structure={structureVersion:1,template:'custom',evaluationDate:'2030-01-01',legs:[leg('AAPL','stock','long',100,100),leg('aapl','call','long',1,12,100),leg('AAPL','call','short',1,5,120),leg('SPY','stock','long',10,400)]};
test('stock and call spread group by normalized underlying with correct combined payoff, multiplier and breakeven',()=>{const groups=payoffGroups(structure);assert.equal(groups.length,2);assert.equal(groups[0].legs.length,3);assert.equal(groups[0].legs.reduce((s,l)=>s+legPayoff(l,110),0),1300);assert.deepEqual(groups[0].breakEven,[103.5]);assert.equal(groups[0].maxLoss,10700);assert.equal(groups[1].maxLoss,4000);});
test('mixed expiries or non-expiry evaluation never fabricate option time value; stock-only groups still chart',()=>{const d=clone(structure);d.legs[2].expiry='2030-02-01';const groups=payoffGroups(d);assert.match(groups[0].error,/估值模型/);assert.ok(groups[1].points.length);d.legs[2].expiry='2030-01-01';d.evaluationDate='2029-12-01';assert.match(payoffGroups(d)[0].error,/估值模型/);});
test('zero payoff intervals, absent inputs and stock entry are not mistaken for live quotes',()=>{const d=clone(structure);d.legs=[leg('A','call','long',1,0,100)];let g=payoffGroups(d)[0];assert.deepEqual(g.zeroIntervals,[[0,100]]);assert.equal(g.reference,null);d.legs[0].entry='';assert.ok(payoffGroups(d)[0].error);assert.equal(rate('',100),null);assert.equal(rate(0,100),0);assert.equal(rate(10,0),null);});
function thesis(title='actual',demo=false){const c=createCase({title,horizon:'2030-01-01',demo});savePlan(c,null,'stock',structure);saveNode(c,'returns',{...c.nodes.returns.data,expectedNet:200,capital:1000,averageLoss:100});setActivePlan(c,c.design.selectedId);return c;}
test('capital basis freezes automatically on first complete active prediction and actual uses the same denominator',()=>{const c=thesis(),basis=clone(c.returnBasis);saveNode(c,'returns',{...c.nodes.returns.data,capital:2000,expectedNet:500});assert.deepEqual(c.returnBasis,basis);saveNode(c,'attribution',{...c.nodes.attribution.data,realized:100});archiveCase(c);assert.equal(completedReturn(c).rate,10);assert.equal(c.performance.basis.rate,20);validateStore({version:1,cases:[c]});});
test('shared history has actual points only plus exactly one current forecast, zero actual preserved, demos excluded',()=>{const old=thesis('old');saveNode(old,'attribution',{...old.nodes.attribution.data,realized:0});archiveCase(old);const demo=thesis('demo',true);saveNode(demo,'attribution',{...demo.nodes.attribution.data,realized:999});archiveCase(demo);const current=thesis('current');const data=historyPoints(current,[old,demo,current]);assert.equal(data.actuals.length,1);assert.equal(data.actuals[0].rate,0);assert.equal(data.predicted.rate,20);assert.equal(data.predicted.id,current.id);current.nodes.returns.data.expectedNet=300;assert.equal(historyPoints(current,[old]).predicted.rate,30);});
test('matrix at 30-90% uses average loss, not maximum loss, and identifies target cells',()=>{const rows=expectancyMatrix({expectedNet:20,capital:1000,averageLoss:100});assert.equal(rows.length,7);assert.ok(Math.abs(rows[0].required-3)<1e-9);assert.equal(rows[0].cells.find(x=>x.b===3).meets,true);assert.ok(Math.abs(rows[0].cells.find(x=>x.b===3).returnRate-2)<1e-9);assert.equal(expectancyMatrix({expectedNet:20,capital:1000})[0].cells[0].meets,null);});

test('missing forecast date does not prevent actual return calculation from manually entered capital',()=>{const c=createCase({title:'undated'});savePlan(c,null,'stock',{structureVersion:1,template:'stock',evaluationDate:'',legs:[leg('A','stock','long',1,100)]});saveNode(c,'returns',{...c.nodes.returns.data,expectedNet:10,capital:100});setActivePlan(c,c.design.selectedId);saveNode(c,'attribution',{...c.nodes.attribution.data,realized:5});archiveCase(c);assert.equal(completedReturn(c).rate,5);assert.equal(historyPoints(c,[c]).predicted,null);validateStore({version:1,cases:[c]});});
