const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),ctx=await browser.newContext({viewport:{width:1500,height:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/data/**',r=>r.fulfill({status:404,body:'test'}));await ctx.route('**/config/risk_policy.json*',r=>r.fulfill({json:{bundles:{Test:{risk_pct:1,total_risk_pct:5,atr_mult:2}}}}));
await page.goto('http://127.0.0.1:8642/workflow.html');
await page.evaluate(async()=>{const m=await import('./assets/workflow-model.mjs');const cases=['AI infrastructure','Consumer recovery','Defensive income'].map((title,i)=>{const c=m.createCase({title});c.nodes.hypothesis.data.rationale='test rationale';m.record(c,'fixture','hypothesis','test');if(i===0)m.transition(c,'hypothesis','running');return c;});localStorage.setItem(m.KEY,JSON.stringify({version:m.VERSION,cases}));});await page.reload();
await page.locator('[data-star]').first().waitFor({state:'attached'});assert.equal(await page.locator('[data-star]').count(),21);assert.equal(await page.locator('.star-label small,.star-label em').count(),0);assert.equal(await page.locator('.star-label').evaluateAll(nodes=>nodes.some(n=>/pending|running|alpha research|portfolio design|position lifecycle|performance attribution/i.test(n.textContent+n.getAttribute('aria-label')))),false);assert.ok(await page.locator('.star-label.is-running').count()>0);assert.ok(await page.locator('.star-label.is-pending').count()>0);assert.equal(await page.locator('.star-label').evaluateAll(nodes=>nodes.every(n=>n.hidden)),true);await page.locator('#galaxy-zoom-in').click();await page.waitForTimeout(350);assert.equal(await page.locator('.star-label').evaluateAll(nodes=>nodes.every(n=>n.hidden)),true);assert.equal(await page.locator('.galaxy-fallback').count(),0);assert.equal(await page.locator('canvas').count()>0,true);assert.equal(await page.locator('#main').isVisible(),false);
await page.locator('[data-filter="active"]').click();assert.equal(await page.locator('#nebula-list').isVisible(),true);assert.equal(await page.locator('#nebula-list').evaluate(el=>el.getBoundingClientRect().left),0);assert.equal(await page.locator('.nebula-list-head > span').count(),4);assert.equal(await page.locator('.nebula-list-row').count(),3);assert.equal(await page.locator('.nebula-list-row').first().locator('.nebula-list-name,.nebula-created,.nebula-list-time,.nebula-more').count(),4);const handle=page.locator('.nebula-drawer-resizer'),beforeWidth=await page.locator('#nebula-list').evaluate(el=>el.getBoundingClientRect().width),box=await handle.boundingBox();await page.mouse.move(box.x+6,box.y+40);await page.mouse.down();await page.mouse.move(box.x+86,box.y+40);await page.mouse.up();const afterWidth=await page.locator('#nebula-list').evaluate(el=>el.getBoundingClientRect().width);assert.ok(afterWidth>beforeWidth+60);assert.equal(await page.evaluate(()=>Number(localStorage.getItem('research-desk.nebula-drawer-width'))),Math.round(afterWidth));await handle.focus();await page.keyboard.press('ArrowLeft');assert.ok(await page.locator('#nebula-list').evaluate((el,w)=>el.getBoundingClientRect().width<w,afterWidth));await page.locator('.nebula-more').first().click();assert.equal(await page.getByRole('button',{name:'存档',exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'删除',exact:true}).count(),1);await page.keyboard.press('Escape');await page.locator('[data-filter="active"]').click();assert.equal(await page.locator('#nebula-list').isHidden(),true);await page.locator('[data-filter="active"]').click();assert.equal(await page.locator('#nebula-list').isVisible(),true);await page.locator('#galaxy-home').click();assert.equal(await page.locator('#nebula-list').isHidden(),true);
assert.match(await page.locator('.galaxy-caption').textContent(),/左键\/单指拖移.*右键旋转.*滚轮\/双指缩放/);await page.waitForTimeout(1100);await page.screenshot({path:'/tmp/galaxy-overview.png'});
assert.equal(await page.locator('[data-star]').evaluateAll(els=>els.every(el=>{const r=el.getBoundingClientRect();return r.top>=198&&r.bottom<=innerHeight;})),true);
const first=page.locator('[data-nebula]').first(),focusedId=await first.getAttribute('data-nebula');await first.click();await page.waitForTimeout(900);assert.equal(await page.locator('[data-star]').evaluateAll((els,id)=>els.filter(el=>!el.dataset.star.startsWith(id+':')).every(el=>el.hidden),focusedId),true);assert.equal(await page.locator('[data-star]').evaluateAll((els,id)=>els.filter(el=>el.dataset.star.startsWith(id+':')).some(el=>!el.hidden),focusedId),true);
const hypothesis=page.locator('[data-star][data-node="hypothesis"]').first();await hypothesis.click();await page.locator('#node-form').waitFor();await page.waitForTimeout(800);assert.equal(await page.locator('.star-label.is-selected').count(),1);assert.ok(await page.locator('.star-label.is-neighbor').count()>0);
await page.locator('[name="f.rationale"]').fill('saved in galaxy');await page.getByRole('button',{name:'保存节点',exact:true}).click();assert.equal(await page.locator('#notice').textContent(),'');assert.equal(await page.locator('[name="f.rationale"]').inputValue(),'saved in galaxy');assert.equal(await page.locator('[data-nebula].is-unsynced').count(),1);await page.locator('#nebula-title').dblclick();await page.locator('#nebula-title-input').fill('AI thesis renamed');await page.locator('#nebula-title-input').press('Enter');assert.equal(await page.locator('#notice').textContent(),'');assert.equal(await page.locator('#nebula-title').textContent(),'AI thesis renamed');assert.equal(await page.locator('[data-nebula].is-unsynced').first().textContent(),'AI thesis renamed');await page.locator('#main').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'/tmp/galaxy-panel.png'});
await hypothesis.click();assert.equal(await page.locator('#main').isVisible(),false);await page.locator('#galaxy-search').fill('Consumer');await page.locator('#cases [data-case]').click();await page.waitForTimeout(800);await page.locator('[data-star][data-node="construction"]').nth(1).click();await page.getByRole('button',{name:'添加 Position',exact:false}).first().waitFor();
await page.locator('#close-star-panel').click();await page.locator('#galaxy-home').click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.waitForTimeout(800);await page.screenshot({path:'/tmp/galaxy-mobile.png'});
await page.locator('#galaxy-search').fill('AI thesis');await page.locator('#cases [data-case]').click();await page.waitForTimeout(800);await page.locator('[data-star][data-node="risk"]').first().click();await page.locator('[name="f.riskBudget"]').waitFor();assert.equal(await page.locator('#rk-risk,#rk-eq,#rk-edge,#rk-invalid').count(),0);assert.equal(await page.locator('#main').isVisible(),true);await page.locator('#close-star-panel').click();await page.reload();assert.equal(await page.locator('#main').isVisible(),false);assert.equal(await page.locator('[data-nebula].is-unsynced').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0].nodes.hypothesis.data.rationale),'saved in galaxy');
await page.locator('[data-filter="active"]').click();let row=page.locator('.nebula-list-row').filter({hasText:'Consumer recovery'});await row.locator('.nebula-more').click();page.once('dialog',d=>d.accept());await row.locator('[data-archive-nebula]').click();assert.equal(await page.locator('.nebula-list-row').count(),2);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases.filter(c=>c.archived).length),1);row=page.locator('.nebula-list-row').filter({hasText:'Defensive income'});await row.locator('.nebula-more').click();page.once('dialog',d=>d.accept());await row.locator('[data-delete-nebula]').click();assert.equal(await page.locator('.nebula-list-row').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases.length),2);
// WebGL failure still provides usable HTML node navigation and editing.
const fallback=await browser.newContext();await fallback.route('**/assets/vendor/3d-force-graph.min.js',r=>r.fulfill({contentType:'text/javascript',body:'window.ForceGraph3D=function(){throw Error("WebGL fixture")};'}));const fp=await fallback.newPage();fp.on('pageerror',e=>errors.push(e.message));await fp.goto('http://127.0.0.1:8642/workflow.html');await fp.evaluate(async()=>{const m=await import('./assets/workflow-model.mjs');localStorage.setItem(m.KEY,JSON.stringify({version:m.VERSION,cases:[m.createCase({title:'Fallback'})]}));});await fp.reload();await fp.locator('.galaxy-fallback [data-star]').first().click();await fp.locator('#node-form').waitFor();await fallback.close();
assert.deepEqual(errors,[]);console.log('PASS WebGL galaxy, 21 stars, focus/neighbors, panel save, close, search, mobile');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
