const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),ctx=await browser.newContext({viewport:{width:1500,height:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/data/**',r=>r.fulfill({status:404,body:'test'}));await ctx.route('**/config/risk_policy.json*',r=>r.fulfill({json:{bundles:{Test:{risk_pct:1,total_risk_pct:5,atr_mult:2}}}}));
await page.goto('http://127.0.0.1:8642/workflow.html');
await page.evaluate(async()=>{const m=await import('./assets/workflow-model.mjs');const cases=['AI infrastructure','Consumer recovery','Defensive income'].map((title,i)=>{const c=m.createCase({title});c.nodes.hypothesis.data.rationale='test rationale';m.record(c,'fixture','hypothesis','test');if(i===0)m.transition(c,'hypothesis','running');return c;});localStorage.setItem(m.KEY,JSON.stringify({version:m.VERSION,cases}));});await page.reload();
await page.locator('[data-star]').first().waitFor();assert.equal(await page.locator('[data-star]').count(),21);assert.equal(await page.locator('.star-label small,.star-label em').count(),0);assert.equal(await page.locator('.star-label').evaluateAll(nodes=>nodes.some(n=>/pending|running|alpha research|portfolio design|position lifecycle|performance attribution/i.test(n.textContent+n.getAttribute('aria-label')))),false);assert.ok(await page.locator('.star-label.is-running').count()>0);assert.ok(await page.locator('.star-label.is-pending').count()>0);assert.equal(await page.locator('.galaxy-fallback').count(),0);assert.equal(await page.locator('canvas').count()>0,true);assert.equal(await page.locator('#main').isVisible(),false);
await page.waitForTimeout(1100);await page.screenshot({path:'/tmp/galaxy-overview.png'});
assert.equal(await page.locator('[data-star]').evaluateAll(els=>els.every(el=>{const r=el.getBoundingClientRect();return r.top>=198&&r.bottom<=innerHeight;})),true);
const first=page.locator('[data-nebula]').first();await first.click();await page.waitForTimeout(900);
const hypothesis=page.locator('[data-star][data-node="hypothesis"]').first();await hypothesis.click();await page.locator('#node-form').waitFor();await page.waitForTimeout(800);assert.equal(await page.locator('.star-label.is-selected').count(),1);assert.ok(await page.locator('.star-label.is-neighbor').count()>0);
await page.locator('[name="f.rationale"]').fill('saved in galaxy');await page.getByRole('button',{name:'保存节点',exact:true}).click();assert.equal(await page.locator('[name="f.rationale"]').inputValue(),'saved in galaxy');assert.equal(await page.locator('[data-nebula].is-unsynced').count(),1);await page.locator('#nebula-title').dblclick();await page.locator('#nebula-title-input').fill('AI thesis renamed');await page.locator('#nebula-title-input').press('Enter');assert.equal(await page.locator('#nebula-title').textContent(),'AI thesis renamed');assert.equal(await page.locator('[data-nebula].is-unsynced').first().textContent(),'AI thesis renamed');await page.locator('#main').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'/tmp/galaxy-panel.png'});
await hypothesis.click();assert.equal(await page.locator('#main').isVisible(),false);await page.locator('#galaxy-search').fill('Consumer');await page.locator('#cases [data-case]').click();await page.waitForTimeout(800);await page.locator('[data-star][data-node="construction"]').nth(1).click();await page.getByRole('button',{name:'添加方案',exact:false}).first().waitFor();
await page.locator('#close-star-panel').click();await page.locator('#galaxy-home').click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.waitForTimeout(800);await page.screenshot({path:'/tmp/galaxy-mobile.png'});
await page.locator('#galaxy-search').fill('AI thesis');await page.locator('#cases [data-case]').click();await page.waitForTimeout(800);await page.locator('[data-star][data-node="risk"]').first().click();await page.locator('#rk-risk').waitFor();assert.equal(await page.locator('#rk-eq').count(),0);assert.equal(await page.locator('#rk-edge').count(),0);assert.equal(await page.locator('#rk-invalid').count(),0);assert.equal(await page.locator('#main').isVisible(),true);await page.locator('#close-star-panel').click();await page.reload();assert.equal(await page.locator('#main').isVisible(),false);assert.equal(await page.locator('[data-nebula].is-unsynced').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0].nodes.hypothesis.data.rationale),'saved in galaxy');
// WebGL failure still provides usable HTML node navigation and editing.
const fallback=await browser.newContext();await fallback.route('**/assets/vendor/3d-force-graph.min.js',r=>r.fulfill({contentType:'text/javascript',body:'window.ForceGraph3D=function(){throw Error("WebGL fixture")};'}));const fp=await fallback.newPage();fp.on('pageerror',e=>errors.push(e.message));await fp.goto('http://127.0.0.1:8642/workflow.html');await fp.evaluate(async()=>{const m=await import('./assets/workflow-model.mjs');localStorage.setItem(m.KEY,JSON.stringify({version:m.VERSION,cases:[m.createCase({title:'Fallback'})]}));});await fp.reload();await fp.locator('.galaxy-fallback [data-star]').first().click();await fp.locator('#node-form').waitFor();await fallback.close();
assert.deepEqual(errors,[]);console.log('PASS WebGL galaxy, 21 stars, focus/neighbors, panel save, close, search, mobile');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
