const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const base=process.env.DASHBOARD_URL||'http://127.0.0.1:8642';
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'}),ctx=await b.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/api.github.com/**',r=>r.abort());
await p.goto(`${base}/workflow.html`);
const id=await p.evaluate(async()=>{const m=await import('./assets/workflow-model.mjs'),c=m.createCase({title:'Legacy position fixture',symbol:'A',horizon:'2030-01-01'});delete c.positionNodeVersion;c.nodes.positions.state='running';c.nodes.positions.data={source:'portfolio',exitRules:'old field',positions:[{symbol:'A',qty:100}],binding:{rules:[{key:'legacy'}]},sync:{status:'ok'}};m.record(c,'legacy positions','positions','fixture');localStorage.setItem(m.KEY,JSON.stringify({version:m.VERSION,cases:[c]}));return c.id;});
await p.reload();await p.locator(`[data-star="${id}:positions"]`).click();await p.locator('.empty-node').waitFor();
assert.equal(await p.locator('#node-form,#wf-position-control,[data-position-key],[data-position-bind],[data-position-refresh]').count(),0);
assert.equal(await p.locator('.empty-node input,.empty-node textarea,.empty-node select').count(),0);
let saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0]);
assert.deepEqual(saved.nodes.positions,{state:'pending',data:{}});assert.equal(saved.positionNodeVersion,1);assert.ok(saved.events.every(e=>Object.keys(e.snapshot.nodes.positions.data).length===0));
await p.locator('[data-transition="running"]').click();saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0]);assert.deepEqual(saved.nodes.positions,{state:'running',data:{}});
await p.locator('[data-transition="pending"]').click();await p.reload();await p.locator(`[data-star="${id}:positions"]`).click();assert.equal(await p.locator('.empty-node').count(),1);assert.deepEqual(errors,[]);
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
if(process.env.SCREENSHOT_PATH)await p.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});console.log('PASS: Position Management migration scrubs live/history fields and leaves an empty state-only star');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
