import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizePortfolio,bindingFromSelection,reconcilePositions,closeOrReleaseRule,validateBindingsAcrossCases,positionLinkFingerprint} from '../assets/position-link.mjs';
import {createCase,gate,record,clone} from '../assets/workflow-model.mjs';
const make=()=>createCase({title:'A thesis',symbol:'A',horizon:'2030-01-01'});
const raw=(qty=100,time='2026-09-22T14:00:00Z')=>({updated_at:time,accounts:[{id:'a',broker:'rh',label:'Test',source_updated_at:time},{id:'b',broker:'rh',label:'Other',source_updated_at:time}],positions:[{account:'a',broker:'rh',kind:'equity',sym:'A',qty,avg_cost:10,price:12},{account:'b',broker:'rh',kind:'option',sym:'A 2030-01-01 15C',qty:2,avg_cost:100,price:150}]});
// These tests cover the retired position-link adapter in isolation. Workflow no longer
// persists its result in Position Management, which is now an intentionally empty node.
function link(c,cases,source,mode='all',qty=100){const binding=bindingFromSelection(c,cases,source,[{key:source.rows[0].key,mode,qty}]);const d=reconcilePositions(c,cases,source,binding);c.nodes.positions.data=clone(d);return d;}
test('account/contract identity and option premium conversion; no invented Greeks',()=>{const s=normalizePortfolio(raw());assert.notEqual(s.rows[0].key,s.rows[1].key);assert.equal(s.rows[1].entry,1);assert.equal(s.rows[1].mark,1.5);const c=make(),b=bindingFromSelection(c,[c],s,[{key:s.rows[1].key,mode:'all'}]),d=reconcilePositions(c,[c],s,b);assert.equal(d.positions[0].delta,'');assert.equal(d.positions[0].qty,2);});
test('whole position follows changes and an adapter snapshot is frozen',()=>{const c=make(),s=normalizePortfolio(raw());link(c,[c],s);record(c,'legacy position snapshot','positions','adapter test');const original=clone(c.events.at(-1).snapshot);const next=raw(120,'2026-09-23T14:00:00Z');next.positions[0].price=14;next.positions[0].avg_cost=11;const d=reconcilePositions(c,[c],normalizePortfolio(next));assert.equal(d.positions[0].qty,120);assert.equal(d.positions[0].entry,11);assert.equal(d.positions[0].mark,14);c.nodes.positions.data=clone(d);assert.equal(original.nodes.positions.data.positions[0].qty,100);});
test('no exclusive overlap and fixed allocations cannot exceed actual quantity',()=>{const a=make(),b=make(),s=normalizePortfolio(raw());link(a,[a,b],s);assert.throws(()=>link(b,[a,b],s),/占用/);const x=make(),y=make();link(x,[x,y],s,'fixed',60);assert.throws(()=>link(y,[x,y],s,'fixed',50),/超过/);link(y,[x,y],s,'fixed',40);validateBindingsAcrossCases([x,y]);const after=reconcilePositions(x,[x,y],normalizePortfolio(raw(80,'2026-09-23T14:00:00Z')));assert.equal(after.sync.status,'attention');assert.equal(after.positions[0].qty,60);assert.match(after.sync.issues[0].message,/超限/);});
test('source disappearance, stale timestamp and fetch/schema errors never erase adapter state',()=>{const c=make();link(c,[c],normalizePortfolio(raw()));let d=reconcilePositions(c,[c],normalizePortfolio(raw(0,'2026-09-23T14:00:00Z')));assert.equal(d.positions[0].qty,100);assert.equal(d.sync.status,'attention');c.nodes.positions.data=clone(d);assert.equal(gate(c,'positions','running'),'');assert.throws(()=>normalizePortfolio(null),/快照/);d=reconcilePositions(c,[c],normalizePortfolio(raw(10,'2026-09-21T14:00:00Z')));assert.equal(d.positions[0].qty,100);assert.match(d.sync.issues[0].message,/早于/);});
test('exit confirmation requires newer source with missing position and does not resurrect on reentry',()=>{const c=make();link(c,[c],normalizePortfolio(raw()));assert.throws(()=>closeOrReleaseRule(c,normalizePortfolio(raw()),c.nodes.positions.data.binding.rules[0].key,'close'),/更新后/);const s=normalizePortfolio(raw(0,'2026-09-23T14:00:00Z')),key=c.nodes.positions.data.binding.rules[0].key,b=closeOrReleaseRule(c,s,key,'close'),d=reconcilePositions(c,[c],s,b);assert.equal(d.positions.length,0);d.notes='对账确认清仓';c.nodes.positions.data=clone(d);assert.equal(gate(c,'positions','running'),'');const reentry=reconcilePositions(c,[c],normalizePortfolio(raw(20,'2026-09-24T14:00:00Z')));assert.equal(reentry.positions.length,0);});
test('release is explicitly distinct from closing; no rebuild-only log churn',()=>{const c=make();const s=normalizePortfolio(raw());link(c,[c],s);const fresh=clone(s);fresh.builtAt='2026-09-23T14:00:00Z';assert.equal(positionLinkFingerprint(reconcilePositions(c,[c],fresh)),positionLinkFingerprint(c.nodes.positions.data));const b=closeOrReleaseRule(c,s,c.nodes.positions.data.binding.rules[0].key,'release');assert.equal(b.rules[0].closedReason,'released');});
test('unsupported option labels and nonstandard multipliers are reported rather than guessed',()=>{const d=raw();d.positions[1].sym='A 1/1 15C';let s=normalizePortfolio(d);assert.equal(s.unsupported.length,1);d.positions[1].sym='A 2030-01-01 15C';d.positions[1].multiplier=150;s=normalizePortfolio(d);assert.equal(s.unsupported.length,1);});
