const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/data/portfolio.json*',r=>r.fulfill({json:{updated_at:'2026-09-22T12:00:00Z',accounts:[],positions:[]}}));await ctx.route('**/config/risk_policy.json*',r=>r.fulfill({json:{account_equity:10000,bundles:{},portfolio:{}}}));await ctx.route('**/data/atr.json*',r=>r.fulfill({json:{}}));
await p.goto((process.env.DASHBOARD_URL||'http://127.0.0.1:8642')+'/workflow.html');await p.locator('#new').click();await p.locator('[name="title"]').fill('Candidate plans');await p.getByRole('button',{name:'创建实例',exact:true}).click();await p.locator('[data-node="construction"]').click();assert.equal(await p.locator('.plan-editor').count(),0);assert.equal(await p.locator('#freeze-design').count(),0);
const save=()=>p.getByRole('button',{name:'保存方案',exact:true}).click();
for(const [name,template] of [['Bull Call Spread','bullCall'],['Long Call','call'],['Long Stock','stock']]){
 await p.locator('#add-plan').click();await p.locator('[name="plan-name"]').fill(name);await p.locator('[name="f.template"]').selectOption(template);await p.locator('#apply-structure-template').click();await p.locator('[name="f.evaluationDate"]').fill('2030-01-01');
 const count=await p.locator('.structure-leg').count();for(let i=0;i<count;i++){await p.locator(`[name="structure${i}.underlying"]`).fill('AAPL');await p.locator(`[name="structure${i}.entry"]`).fill(template==='stock'?'100':i?'5':'12');if(template!=='stock'){await p.locator(`[name="structure${i}.expiry"]`).fill('2030-01-01');await p.locator(`[name="structure${i}.strike"]`).fill(i?'120':'100');}}
 await save();assert.equal(await p.locator('.plan-editor').count(),0);
}
let c=await p.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0]);const [a,b,stock]=c.design.plans.map(x=>x.id);assert.equal(c.design.plans.length,3);
await p.locator(`[data-plan-row="${a}"] [data-plan-menu]`).click();assert.equal(await p.locator('.plan-editor').count(),0);await p.locator(`[data-active-plan="${a}"]`).click();assert.match(await p.locator(`[data-plan-row="${a}"]`).getAttribute('class'),/in-action-policy/);assert.equal(await p.locator(`[data-plan-row="${a}"] .plan-name-button`).evaluate(e=>getComputedStyle(e).color),'rgb(255, 118, 127)');
await p.locator(`[data-plan-row="${b}"] td`).nth(1).click();await p.locator('[name="plan-name"]').fill('Call alternative');await save();assert.equal(await p.locator('.in-action-policy').count(),1);
await p.locator('[data-node="returns"]').click();assert.equal(await p.locator('#design-plan-selector option').count(),3);await p.locator('#design-plan-selector').selectOption(a);await p.locator('[name="f.expectedNet"]').fill('100');await p.getByRole('button',{name:'保存节点',exact:true}).click();await p.locator('#design-plan-selector').selectOption(b);assert.equal(await p.locator('[name="f.expectedNet"]').inputValue(),'');await p.locator('[name="f.expectedNet"]').fill('120');await p.getByRole('button',{name:'保存节点',exact:true}).click();await p.locator('#design-plan-selector').selectOption(a);assert.equal(await p.locator('[name="f.expectedNet"]').inputValue(),'100');
await p.locator('[data-node="risk"]').click();await p.locator('#rk-risk').waitFor();assert.equal(await p.locator('#design-plan-selector').count(),0);assert.equal(await p.locator('[name="f.lossBudget"]').count(),0);assert.equal(await p.locator('#rk-eq').count(),0);assert.equal(await p.locator('#rk-edge').count(),0);assert.equal(await p.locator('#rk-invalid').count(),0);
c=await p.evaluate(()=>JSON.parse(localStorage.getItem('research-desk.workflow.v1')).cases[0]);const historical=c.events.at(-1).id;
await p.locator('[data-node="construction"]').click();assert.equal(await p.locator('.plan-editor').count(),0);p.on('dialog',d=>d.accept());await p.locator(`[data-plan-row="${a}"] [data-plan-menu]`).click();await p.locator(`[data-delete-plan="${a}"]`).click();assert.equal(await p.locator('.in-action-policy').count(),0);await p.locator('[data-node="returns"]').click();assert.equal(await p.locator('#design-plan-selector option').count(),2);assert.equal(await p.locator('[name="f.expectedNet"]').inputValue(),'120');
await p.locator('[data-node="construction"]').click();await p.locator(`[data-replay="${historical}"]`).click();assert.equal(await p.locator('[data-plan-row]').count(),3);await p.locator(`[data-edit-plan="${a}"]`).click();assert.equal(await p.locator('[name="plan-name"]').inputValue(),'Bull Call Spread');assert.equal(await p.locator('[name="plan-name"]').isDisabled(),true);await p.locator('#exit-replay').click();assert.equal(await p.locator('.plan-editor').count(),0);
await p.reload();await p.locator('[data-node="construction"]').click();assert.equal(await p.locator('[data-plan-row]').count(),2);assert.equal(await p.locator('.plan-editor').count(),0);
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.SCREENSHOT_PATH)await p.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: three candidate plans, hidden editor, naming, red policy, independent returns, shared risk, deletion sync, immutable replay, reload, mobile');await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
