import test from 'node:test';
import assert from 'node:assert/strict';
import {VERSION,NODES,record,archiveCase,createCase,demoCase,gate,transition,saveNode,clone,validateStore} from '../assets/workflow-model.mjs';
test('new theses start with one shared bull/base/bear underwriting distribution',()=>{const c=createCase({title:'scenario'}),d=c.nodes.returns.data;assert.equal(d.scenarioVersion,1);assert.deepEqual(d.scenarios.map(x=>x.id),['bull','base','bear']);assert.deepEqual(d.scenarios.map(x=>x.probability),[25,50,25]);});
test('editing preserves manual progress and immutable history',()=>{const c=demoCase(),snapshot=clone(c.events.at(-1).snapshot),data=clone(c.nodes.construction.data);data.legs[0].qty=30;saveNode(c,'construction',data);assert.equal(c.nodes.construction.state,'running');assert.deepEqual(c.events.at(-2).snapshot,snapshot);validateStore({version:VERSION,cases:[c]});});
test('all nodes switch pending/running without reason or required content',()=>{const c=createCase({title:'test',symbol:'A',horizon:'2030-01-01'});assert.deepEqual(c.nodes.hypothesis.data,{expectation:'',rationale:'',verification:'',invalidation:''});for(const key of Object.keys(NODES)){assert.equal(gate(c,key,'running'),'');transition(c,key,'running');transition(c,key,'pending');assert.equal(c.nodes[key].state,'pending');}assert.equal(c.events.at(-1).reason,'');assert.throws(()=>transition(c,'hypothesis','valid'),/不可用/);validateStore({version:VERSION,cases:[c]});});
test('archive is separate from node progress and preserves readonly roundtrip',()=>{const c=demoCase();archiveCase(c);assert.equal(c.archived,true);assert.ok(Object.values(c.nodes).every(n=>['pending','running'].includes(n.state)));assert.throws(()=>saveNode(c,'hypothesis',{}),/只读/);assert.deepEqual(validateStore({version:VERSION,cases:[c]}).cases[0],c);});
test('legacy migration maps old state and permanently scrubs Position Management snapshots',()=>{
 const c=createCase({title:'legacy',symbol:'A',horizon:'2030-01-01'});delete c.stateVersion;delete c.positionNodeVersion;
 const states={hypothesis:'valid',signal:'triggered',returns:'evaluated',construction:'baseline',risk:'within',positions:'closed',attribution:'archived'};
 for(const [key,state] of Object.entries(states))c.nodes[key].state=state;
 c.nodes.positions.data={source:'portfolio',exitRules:'legacy rule',positions:[{type:'stock',side:'long',qty:10,entry:100}],binding:{rules:[{key:'legacy'}]},sync:{status:'ok'}};
 c.nodes.hypothesis.data={direction:'bullish',target:10,rationale:'old rationale',invalidation:'old invalidation'};c.archived=true;c.events=[];c.revision=0;record(c,'old archive','attribution','old reason');
 const originalHypothesis=clone(c.events[0].snapshot.nodes.hypothesis),store=validateStore({version:VERSION,cases:[c]}),m=store.cases[0];
 assert.deepEqual(m.events[0].snapshot.nodes.hypothesis,originalHypothesis);assert.ok(m.events.every(e=>e.snapshot.positionNodeVersion===1&&['unlinked','pending'].includes(e.snapshot.nodes.positions.state)&&Object.keys(e.snapshot.nodes.positions.data).length===0));assert.equal(m.positionNodeVersion,1);assert.deepEqual(m.nodes.positions,{state:'pending',data:{}});assert.equal(m.archived,true);assert.match(m.nodes.hypothesis.data.expectation,/10%/);assert.equal(m.nodes.hypothesis.data.rationale,'old rationale');assert.equal(m.nodes.hypothesis.data.direction,undefined);assert.equal(m.stateVersion,2);assert.deepEqual(validateStore(store),store);
});
test('reject corrupt history, duplicate cases, and invalid legs in backups',()=>{const c=demoCase();assert.throws(()=>validateStore({version:VERSION,cases:[c,c]}),/重复/);const bad=clone(c);bad.events[0].snapshot.id='wrong';assert.throws(()=>validateStore({version:VERSION,cases:[bad]}),/不匹配/);const data=clone(c.nodes.construction.data);data.legs[1].qty=.5;assert.throws(()=>saveNode(c,'construction',data),/整数/);});
